name: Laravel CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql, zip, exif, bcmath

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate app key
      run: php artisan key:generate

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: npm install
    
    - name: Build frontend assets
      run: npm run build

    - name: Wait for MySQL
      run: |
        for i in {1..30}; do
          mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;" && break
          sleep 1
        done

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test
